// <auto-generated />
using System;
using EfCoreTemporalTable.Test.SampleModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreTemporalTable.Test.SampleModel.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20210128223620_InitialDbConfiguration")]
    partial class InitialDbConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EfCoreTemporalTable.Test.SampleModel.ExampleEntity1", b =>
                {
                    b.Property<int>("ExampleEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstMappedProperty");

                    b.Property<Guid>("FourthProperty")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FourthMappedProperty")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SecondProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecondMappedProperty");

                    b.Property<DateTime>("ThirdProperty")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThirdMappedProperty");

                    b.HasKey("ExampleEntityId");

                    b.ToTable("ExampleEntity1");
                });
#pragma warning restore 612, 618
        }
    }
}
